# Generated by Django 5.0.4 on 2024-05-04 17:20

import common.utils
import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinics', '0001_initial'),
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('subtitle', models.CharField(max_length=100, verbose_name='subtitle')),
                ('for_what', models.CharField(max_length=100, verbose_name='for what')),
                ('short_desc', models.TextField(verbose_name='short description')),
                ('desc', models.TextField(verbose_name='description')),
                ('price', models.IntegerField(verbose_name='price')),
                ('is_home_page', models.BooleanField(default=False, unique=True, verbose_name='is home page')),
                ('gif', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_gif', to='common.media', verbose_name='gif')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.media', verbose_name='image')),
            ],
            options={
                'verbose_name': 'service',
                'verbose_name_plural': 'services',
            },
        ),
        migrations.CreateModel(
            name='ProcedureCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('price', models.CharField(max_length=100, verbose_name='price')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedure_costs', to='services.service', verbose_name='service')),
            ],
            options={
                'verbose_name': 'procedure cost',
                'verbose_name_plural': 'procedure costs',
            },
        ),
        migrations.CreateModel(
            name='OrderService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=100, validators=[common.utils.validate_phone_number], verbose_name='Phone')),
                ('full_name', models.CharField(max_length=100, verbose_name='full name')),
                ('book_date', models.DateField(verbose_name='book date')),
                ('status', models.CharField(choices=[('new', 'new'), ('accepted', 'accepted'), ('progress', 'progress'), ('canceled', 'canceled'), ('finished', 'finished')], default='new', max_length=100, verbose_name='status')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.service', verbose_name='service')),
            ],
            options={
                'verbose_name': 'order service',
                'verbose_name_plural': 'order services',
            },
        ),
        migrations.CreateModel(
            name='Characteristic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('value', models.CharField(max_length=100, verbose_name='value')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characteristics', to='services.service', verbose_name='service')),
            ],
            options={
                'verbose_name': 'characteristic',
                'verbose_name_plural': 'characteristics',
            },
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('order', models.IntegerField(default=0, verbose_name='order')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='services.servicecategory')),
            ],
            options={
                'verbose_name': 'Service Category',
                'verbose_name_plural': 'Service Categories',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='services.servicecategory', verbose_name='category'),
        ),
        migrations.CreateModel(
            name='ServiceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.media', verbose_name='image')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='services.service', verbose_name='service')),
            ],
            options={
                'verbose_name': 'service image',
                'verbose_name_plural': 'service images',
            },
        ),
        migrations.CreateModel(
            name='WhoPerformsProcedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='who_performs_procedures', to='services.service', verbose_name='service')),
                ('specialist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedures', to='clinics.specialist', verbose_name='specialist')),
            ],
            options={
                'verbose_name': "Specialist's service",
                'verbose_name_plural': "Specialist's services",
            },
        ),
    ]
